### ISSUE TITLE
Not compatible with 1.9

### ISSUE THREAD

**Issue by BenLem** [trentech/EasyKits#1]
EasyKit is a **great** plugin, really, I love it, but unfortunately it's not compatible with Spigot 1.9 :
There's no error in the logs until a try to give me a kit, and then …

`[11:11:00 ERROR]: Invalid inventory size; expected 36 or less`

Which is pretty understandable ^^'
I really hope you'll update the plugin soon, it's the last plugin I need updated to upgrade my server to Spigot 1.9 and, as I said, I love it <3

Thank you

**Comment by astr1al** [comment]
Sorry to get your hopes up with a reply, but I have the same error. I hope this plugins gets an update soon.

**Comment by BenLem** [comment]
Yep, It would be fantastic ! <3

**Comment by trentech** [comment]
This version of EasyKits is for Sponge, not bukkit. Your looking for this
https://github.com/trentech/EasyKits_Bukkit
