### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by SomeoneLol** [trentech/EasyKits#2]
When non-op players do /kit kitname  they see "you don't have permission" when OP do it it gives them the kit. How do I fix this?

**Comment by trentech** [comment]
easykits.kit.<kitname>

**Comment by SomeoneLol** [comment]
Where is that?

**Comment by SomeoneLol** [comment]
![screenshot_20190213-065451](https://user-images.githubusercontent.com/47545003/52710289-fd057200-2f5c-11e9-8d0f-023e03b86e45.png)

**Comment by SomeoneLol** [comment]
Nvm I figured it out ty
